#server
server:
  port: 10000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: root
    password:


  #jpa
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      #jpa ddl-auto
      #create: DROP ? CREATE
      #create-drop: DROP ? CREATE ? DROP, DML? ???? ?? ?? DROP?? ??
      #update: Entity? DB ??? ?? ? ?? ?? ??(?? ??)
      #validate: Entity? DB ??? ??(??? ?? ??)
      ddl-auto: update


  #log
  output:
    ansi:
      enabled: always


  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB