#server
server:
  port: 10000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    jdbc:mysql://localhost:3306/DB name?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/restaurant-project?serverTimezone=America/New_York
    username: root
    password:


  #jpa
  jpa:
    hibernate:
      ddl-auto: create-drop   # 처음엔 update, 나중엔 validate 추천
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


  #log
  output:
    ansi:
      enabled: always


  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB